GEMINI_API_KEY = "AIzaSyAQ0F3G0u-MnzC56TZEgai7neWZcGh54Sw"   # твой ключ из Google AI Studio
HF_TOKEN = "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"          # твой токен Hugging Face
DEEPSEEK_API_KEY = "sk-07159e18e36b43919b2e20594af7de34"